
void lcd_init(void);
void lcd_write(char data);
void lcd_cmd(char data);
void lcd_data(char data);
void delay_ms(int a);
void delay_us(int a);
void initial_time(int hour,int min,int sec);
void initial_data(int date,int month,int year);
void initial_day(int day);
void gettimeinfo(int *,int *,int*);
void lcd_display_time(int hour,int min,int sec);
void getdatainfo(int *date,int *month,int *year);
void lcd_display_data(int date,int month,int sec);
void lcd_string(int year);
void getdayinfo(int *day);
void lcd_display_day(int day);
void lcd_string1(char *s);
void initial_alarm(int hour,int min,int sec);
void initial_alarm_data(int date,int momth,int year);
void initial_alarm_day(int day);
void kpm_init(void);
char keyscan(void);
char colscan(void);
char rowcheck(void);
char colcheck(void);
int readnum(int *,int *);
void display_alarm(int al_hour,int al_min,int al_sec);
int check_password(void);
void check_and_print_alarm(void);
void adc_init(void);
void adc_read(int chno,int *dval,float *evr);
void read_lm35(int *tdegC);
void rtc_change(void);
void password_change(void);
void Alarm_change(void);
